name: lekker_lokaal_app
description: De mobiele applicatie voor handelaars van Lekker Lokaal.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

  sqflite: any
  path_provider: any
  barcode_scan: any
  date_format: any
  local_auth: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/LoginIcon.png
    - assets/alucard.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf